# basic settings for pygame project

# colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

# screen settings
WIDTH = 800
HEIGHT = 550
FPS = 30

# game settings
PIXELSIZE = 2
TILESIZE = 64
PLAYER_SPEED = 0.2
MOVEMENT_BUFFER = 0.17

# camera settings
CAMERA_WIDTH = 14
CAMERA_HEIGHT = 7.5
GAME_SURF_HEIGHT = WIDTH/CAMERA_WIDTH*CAMERA_HEIGHT
INVENTORY_HEIGHT = HEIGHT - GAME_SURF_HEIGHT
SCALE_FACTOR = WIDTH/CAMERA_WIDTH/TILESIZE

# layers
PLAYER_LAYER = 10
TILE_LAYER = 0

